spring:
  datasource:
    url: jdbc:postgresql://localhost:${DB_HOST_PORT:5458}/${DB_NAME:backtemplate}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    enabled: true
